Skip action if there is no file to upload
Signed-off-by: S I P U N <sipunkumar85@gmail.com>

diff --git a/.github/workflows/telegram.yml b/.github/workflows/telegram.yml
--- a/.github/workflows/telegram.yml
+++ b/.github/workflows/telegram.yml
@@ -33,13 +33,20 @@ jobs:
         id: assets
         run: |
           set -e
+          url="https://api.github.com/repos/${{ github.repository }}/releases/tags/${TAG}"
           resp=$(curl -sSf -H "Authorization: Bearer $GH_TOKEN" \
             -H "Accept: application/vnd.github+json" \
-            https://api.github.com/repos/${{ github.repository }}/releases/tags/${TAG})
+            "$url" || true )
+          if echo "$resp" | grep -q '"Not Found"'; then
+            echo "Release for tag ${TAG} not found (probably no updates). Exiting."
+            echo "NO_APKS=1" >> $GITHUB_ENV
+            exit 0
+          fi
           echo "$resp" | jq -r '.assets[] | select(.name|test("_v.*\\.apk$")) | [.name, .browser_download_url] | @tsv' > urls.tsv
           if [ ! -s urls.tsv ]; then
             echo "No APK assets found on release ${TAG}. Exiting."
             echo "NO_APKS=1" >> $GITHUB_ENV
+            exit 0
           fi
 
       - name: Exit if no APKs
